name: CI - Changelog
on:
  push:
    branches: [ main ]

jobs:
  changelog-prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: $GITHUB_TOKEN
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CI - Update changelog
          file_pattern: CHANGELOG.md
