name: CI - Changelog
on:
  push:
    branches: [ master ]

jobs:
  changelog-prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: changelog

      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          issues: false
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: true
          unreleased: true
          sinceTag: "1.5.0"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: changelog
          commit_message: CI - Update changelog
          file_pattern: CHANGELOG.md

      - name: Http
        run: mkdir -p http

      - name: Create log directories
        working-directory: http/
        run: mkdir -p \
          var/log/adyen \
          var/log/api_logger \
          var/log/peoplevox \
          var/log/intelligent_return \
          var/report

      - name: LS
        working-directory: http/
        run: ls -la

      - name: Create log directories
        working-directory: http/
        run: mkdir -p var/log/adyen var/log/api_logger var/log/peoplevox var/log/intelligent_return var/report

      - name: LS
        working-directory: http/
        run: ls -la
