name: Promote

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.35.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false

  update-changelog:
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v2
        with:
          ref: changelog

      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          issues: false
          issuesWoLabels: false
          pullRequests: true
          prWoLabels: true
          maxIssues: 3

      - uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          branch: changelog
          commit_message: CI - Update changelog for tag ${{ needs.tag.outputs.tag }}
          file_pattern: CHANGELOG.md

  create-release:
    runs-on: ubuntu-latest
    needs: [tag, update-changelog]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: changelog

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ needs.tag.outputs.tag }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          release_name: Release ${{ needs.tag.outputs.tag }} ()
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false
